
#正式数据库配置信息
jdbc:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://192.168.252.33:1433;DatabaseName=KuKaSaleTar
  username:
  password:

dubhe:
  appKey : app1000sup
  secret : ea972c4514a1d3534534sdrfdra745ca32c7aa439b
  dubheUrl : http://dubhe-test.iyaolian.cn:81/router/dubhe/service
  tenantCode : ylkj